### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Talianash** [williamgilpin/pypdb#25]
Hello!
I've tired to install the package, but demos.ipynb didn't work until I used the command
`pip install --user .`

When I used `pip install pypdb`, python failed to find **pypdb.clients** module and when downloaded repository and used `python setup.py install`, python failed to find **pypdb.clients.search.operators** module. 

My os is macOS Mojave 10.14.6, I use conda 4.9.2.

**Comment by williamgilpin** [comment]
Hello, thank you very much. I think part of the issue is that I haven't yet updated the version on PyPI. I will do that.

If you `pip uninstall pypdb` and then run `python setup.py install` do you still have issues? I can't replicate that issue, but I might need to check my env a little more carefully.

**Comment by Talianash** [comment]
Did so, `import pypdb` works fine, but `from pypdb.clients.search.search_client import perform_search` still raises "ModuleNotFoundError: No module named 'pypdb.clients.search.operators'".
Is there any other information from me that may be helpful? :)

**Comment by williamgilpin** [comment]
Just to double check, is this all with the latest version? My apologies for the inconvenience; I'm having a bit of trouble replicating this issue
