### ISSUE TITLE
PDBs have 0 atoms

### ISSUE THREAD

**Issue by dmyersturnbull** [williamgilpin/pypdb#4]
```python
import pypdb
p = pypdb.describe_pdb('2H8N')
print(p['resolution']) # prints 2.60
print(p['nr_atoms']) # prints 0
```

Same thing with `4lza`.

**Comment by williamgilpin** [comment]
@dmyersturnbull thanks for the report, I'll take a look at the raw xml for those entries to see if it's an issue with the PDB or with pypdb's parsing.

**Comment by williamgilpin** [comment]
@dmyersturnbull thanks for checking this out. It looks like the problem is that the RCSB PDB doesn't have any information about the number of atoms in the entry, and so it returns zero. I can change this to a string like "n/a" in a future release, but for now I can only suggest using `p['nr_residues']` or using the get_all_info function to get information about weight, which might be closer to what you are looking for:

`p = get_all_info('2h8n')`
`p['@weight']`
