### ISSUE TITLE
Adding PDB chain functionality: Chain Sequence, Chain Description, Chain Name, Taxonomy etc.

### ISSUE THREAD

**Issue by lacoperon** [williamgilpin/pypdb#6]
Hi there,

For a project I'm doing, I'm using the RCSB API to get information about the particular chain-level information associated with a given PDB stored in the Data Bank.

For example, using various APIs, you can get the chain name (ie 'A'), chain description (ie 'yeast S12 protein', taxonomy (ie 'S. cerevisiae'), and if you do a join on two queries, other information like the sequence associated with said chain ('ATGAAATAG').

I was wondering if this sort of query would be useful with respect to this API, given that I've already pretty much implemented the logic in a repo which I wrote to query the RCSB API (having not heard about your project until now).

Thanks,
- Elliot

**Comment by williamgilpin** [comment]
Hello @lacoperon , this sounds great---which functions from your repo would you like to see consolidated? I would welcome a pull request adding this in, since it sounds like it would be an addition that will not affect the modify the functionality of the other functions. However, we should double check to see if the request structure is the same as everything else in the package.
